### ISSUE TITLE
Having a start time column on the left, and an end time column on the right

### ISSUE THREAD

**Issue by rdamore** [itsmeichigo/DateTimePicker#1]
Other than that, this pod is absolutely unreal. Thanks a bunch!

**Comment by itsmeichigo** [comment]
Thank you, I have update the lib and pod. Cheers!

**Comment by rdamore** [comment]
Hey, thanks for the quick reply and the update! I think I wasn't very clear with my comment. What I meant was to have the possibility of picking a date (which is already there) but then having a start time picker next to an end time picker below picking the date. So basically having 2 of these, 1 for start time, 1 for end time:
![screen shot 2016-10-01 at 3 16 27 am](https://cloud.githubusercontent.com/assets/17229438/19012493/7d664384-8785-11e6-91d9-10f65107eaf1.png)
