### ISSUE TITLE
Haptic Feedback

### ISSUE THREAD

**Issue by maschoffjake** [itsmeichigo/DateTimePicker#100]
It's hard to tell when you have completely selected a new element from the TimePicker. 
I was wondering if it'd be possible to add some haptic feedback to when you are scrolling like Apple's DateTimePicker? Or at least an ability to enable haptic feedback

**Comment by itsmeichigo** [comment]
Thanks for the suggestion. Right now I’m a bit caught up with other projects so this may take a while. You’re welcome to contribute though, since this repo is open and I really appreciate help from the community. Have a nice day!
