### ISSUE TITLE
MinuteInterval add case sixty

### ISSUE THREAD

**Issue by Washington-dev** [itsmeichigo/DateTimePicker#103]
Thank you very much for your DateTimePicker

We will use DateTimePicker for our school app, unfortunately it does not have hour selection, and hour features is the only thing we need.

Can you please help adding 『case sixty = 60』 to enum MinuteInterval.

Thank you very much.

![thirtyMinute](https://user-images.githubusercontent.com/67935037/92449180-4165fc00-f1ec-11ea-8a09-ed35d9048dfe.png)

**Comment by itsmeichigo** [comment]
@Washington-dev for specific use cases please fork the library and update it to your needs. This is not the intended behavior for the picker and not many users can benefit from it so I'd prefer not to update it - sorry.
