### ISSUE TITLE
Date is not showing at all

### ISSUE THREAD

**Issue by tirthendudass** [itsmeichigo/DateTimePicker#106]
Opening the picker does not show date. 

![Simulator Screen Shot - iPhone 6s - 2020-10-30 at 00 42 02](https://user-images.githubusercontent.com/73666296/97621525-02646200-1a49-11eb-9638-242b494e9ddf.png)

**Comment by tirthendudass** [comment]
@itsmeichigo : Thank you so much for the fix. I really really appreciate it.

**Comment by itsmeichigo** [comment]
You can see the commit referenced above. I'll bump the library version soon, for now you can checkout at the latest commit for the fix.

**Comment by tirthendudass** [comment]
@itsmeichigo : Thank you so much for the fix. I really really appreciate it.
