### ISSUE TITLE
How can I disable automatic selection?

### ISSUE THREAD

**Issue by beom-mingyu** [itsmeichigo/DateTimePicker#107]
...
private func alignCollectionView(_ collectionView: UICollectionView) {
        let centerPoint = CGPoint(x: collectionView.center.x + collectionView.contentOffset.x, y: 50);
        if let indexPath = collectionView.indexPathForItem(at: centerPoint) {
            // automatically select this item and center it to the screen                <<----Not to be selected!
            // set animated = false to avoid unwanted effects
            collectionView.selectItem(at: indexPath, animated: false, scrollPosition: .top)
            if let cell = collectionView.cellForItem(at: indexPath) {
                let offset = CGPoint(x: cell.center.x - collectionView.frame.width / 2, y: 0)
                collectionView.setContentOffset(offset, animated: false)
            }
...

How can I disable automatic selection?

**Comment by itsmeichigo** [comment]
Hi, currently there's no option to disable the selection so if you need custom behaviors you can fork the library and update it to your needs.

**Comment by beom-mingyu** [comment]
ok, thank u

**Comment by palla89** [comment]
done in pull request #112 !
