### ISSUE TITLE
Start at center when minimum date = current date?

### ISSUE THREAD

**Issue by Amefuri** [itsmeichigo/DateTimePicker#11]
Hi first of all , Thank you for this cool date picker !!

Is there's an easy way to handle this situation where I have current date as minimum.
ex:
```
let min = current
let max = Date().addingTimeInterval(60 * 60 * 24 * 365)
let picker = DateTimePicker.show(selected: self.current, minimumDate: min, maximumDate: max)
```
![screen shot 2559-11-03 at 1 03 31 pm](https://cloud.githubusercontent.com/assets/1732314/19957096/2a8cb070-a1c6-11e6-9ac7-272d3cb474a2.png)

but my expected result is like this:

![screen shot 2559-11-03 at 1 04 31 pm](https://cloud.githubusercontent.com/assets/1732314/19957104/44e00418-a1c6-11e6-94b2-437f3904aae9.png)

Thank you,

**Comment by itsmeichigo** [comment]
Hi, I think it's a good idea to always center the cell, so I updated the control to adopt the behavior. You can try out the new code now :]

**Comment by Amefuri** [comment]
Thank you @itsmeichigo  ><
