### ISSUE TITLE
Get Only view

### ISSUE THREAD

**Issue by SLAMAKA** [itsmeichigo/DateTimePicker#12]
hello, i'm noob in swift and iOS developing
i want replace keyboard to date picker view(like: textfield.inputView = picker) when clicked button. but it's not working. picker cover textfield.
how to resolved this problem?!) 

p.s 👍 good library. my isn't perfect)

**Comment by itsmeichigo** [comment]
Maybe you want to put a clear button on top of the text field? So when you tap to change content of the text field, the button will receive the touch and fire event to show the date picker. Let me know how that works for you.
