### ISSUE TITLE
Change the date format appear on the top of the picker.

### ISSUE THREAD

**Issue by Rashesh-Bosamiya** [itsmeichigo/DateTimePicker#14]
I want to change the date format that appears on the top of the picker.

**Comment by daviskoh** [comment]
any update on this as well?

**Comment by itsmeichigo** [comment]
Hi, you can change the format using variable `dateFormat`.

**Comment by daviskoh** [comment]
Hi. Thanks for replying so quickly! Is it possible to have the dateFormat as 12hr format as well? I know the picker has the `is12HourFormat` property.

**Comment by itsmeichigo** [comment]
Yes you can check the demo project to see how it is implemented. I'll update the ReadMe file for better documentation, sorry for the inconvenience.
