### ISSUE TITLE
Suggestion: only allow user to select time after minDate

### ISSUE THREAD

**Issue by kevinxh** [itsmeichigo/DateTimePicker#15]
If I set minimumDate to now, the picker still allows user to pick earlier time today.

It should restrict user to only pick time after now.

**Comment by itsmeichigo** [comment]
Did you test with the latest code? If so, pls explain further the issue, because I couldn't reproduce the bug.

**Comment by JYNiMing** [comment]
If you pick the first DateCollectionViewCell，click "DONE" then click "Pick", It will reproduce  the but: assertion failed: Selected date should be later or equal to minimum date.

**Comment by lzuccaro** [comment]
Hi,
I'm experiencing the same issue. 

If I set the minimumDate, I can still select a time before the minimumDate. 
The date selection works properly, instead.

STEPS TO REPRODUCE:
1. Set the minimumDate (i.e. now).
2. Select a time before the minimumDate.
3. Click Done.

ACTUAL RESULT:
The picker returns a date+time before the minimumDate.

EXPECTED RESULT:
Prevent selecting time before the minimumDate

**Comment by itsmeichigo** [comment]
Hi all,

Thanks for reporting the issue. I have pushed the fix for this in the latest commit, hope it helps.
Also, apologies for the late response. 

Cheers!

**Comment by lzuccaro** [comment]
It works!
Thanks
