### ISSUE TITLE
Carthage Integration

### ISSUE THREAD

**Issue by bennokress** [itsmeichigo/DateTimePicker#16]
I would like to be able to integrate DateTimePicker to my project via Carthage instead of Cocoa Pods, sadly right now this is not possible: `Dependency "DateTimePicker" has no shared framework schemes`

I'm not experienced enough to know if this is a complex task, but maybe you can look into this.

**Comment by StuSchwartz** [comment]
I would also like to use DateTimePicker, but cannot since I am using Carthage.

**Comment by itsmeichigo** [comment]
A bit late, but Carthage is supported in version 2.1.0 onward.
