### ISSUE TITLE
Default selectedDate:

### ISSUE THREAD

**Issue by Rashesh-Bosamiya** [itsmeichigo/DateTimePicker#21]
`picker.selectedDate`

Does change the _title Date_ that appears on the top of picker. But **doesn't** the change actual date that is on centre of `collectionView`.

Please let me know fix ASAP.

**Comment by itsmeichigo** [comment]
Hi,

You can add your `selectedDate` in the `show` function to make the collection view display the date you chose, as this is an optional parameter in the function:

`@objc open class func show(selected: Date? = nil, minimumDate: Date? = nil, maximumDate: Date? = nil) -> DateTimePicker`

Cheers.

**Comment by Rashesh-Bosamiya** [comment]
Thanks!

One more thing, I want a cancel button on top left/right to dismiss the date picker.

Currently once the date picker is presented there is no way to dismiss other than select the date.

So, how can I achieve this?

**Comment by itsmeichigo** [comment]
Actually it's one of the enhancements I'm about to implement. Currently if you wish to have that feature, I'd recommend you fork my repo and customize it to your needs.

Thanks.
