### ISSUE TITLE
How can we change to 12hr format

### ISSUE THREAD

**Issue by ghost** [itsmeichigo/DateTimePicker#22]
How can we change to the AM and PM

**Comment by itsmeichigo** [comment]
Hi, this has been implemented in the latest commit. Cheers!

**Comment by pprevalon** [comment]
Please take a look the date listed above the picker. when AM is selected the date is listed as 12hr format. when you select PM it goes back to 24 hr when it should still be 12hr.
my code 



`let picker = DateTimePicker.show()
            picker.is12HourFormat = true
            picker.highlightColor = UIColor(red:0.42, green:0.73, blue:0.94, alpha:1.0)
            picker.completionHandler = { date in
                // do something after tapping done
                print(date)
            }
`
![image](https://cloud.githubusercontent.com/assets/19171619/24520429/6b5c0674-1556-11e7-8323-2bb41ab3737c.png)
![image](https://cloud.githubusercontent.com/assets/19171619/24520433/6f832444-1556-11e7-97b7-e1900fcae035.png)
