### ISSUE TITLE
How can I hide time picker?

### ISSUE THREAD

**Issue by Rashesh-Bosamiya** [itsmeichigo/DateTimePicker#24]
I want to show only Date Picker, not Time Picker?
And when Time Picker is Hide, the size of picker would be decreased.?

**Comment by jadore801120** [comment]
Hi, would you mind to provide an example about the usage of the api to hide the time picker?
Thanks!

Yu-Hsiang

**Comment by itsmeichigo** [comment]
Hi @jadore801120 , I have updated the ReadMe file for this. Basically all you need to add is `picker.isDatePickerOnly = true`. 

Cheers

**Comment by jadore801120** [comment]
Hi @itsmeichigo, thanks for your quick reply and this great repo!

Yu-Hsiang

**Comment by Rashesh-Bosamiya** [comment]
Thanks 🥇
