### ISSUE TITLE
Change the background color of the Done button and the textColor of the Cancel Button

### ISSUE THREAD

**Issue by flstrout** [itsmeichigo/DateTimePicker#29]
Changing the darkColor property does not change the Done button's background or the Cancel button's textColor. I am not sure if this was intentional or not.

I was able to fix this by adding a didSet to the darkColor's declaration in the DateTimePicker class like you did in the highlightColor's declaration.

If this is not the desired behavior you were intending then it would be very helpful if you would create a way for us to change these controls' visual properties.

**Comment by itsmeichigo** [comment]
Hi, thanks for pointing out the issue. I must have left out this without even recognizing. Will push a commit to fix this asap.

**Comment by flstrout** [comment]
Also the second colon in 12 hr mode does not conform to the highlightColor like the first colon does.
The highlightColor didSet is missing:
colonLabel2.textColor = highlightColor

**Comment by itsmeichigo** [comment]
That's true, I saw that issue just now hahha.
