### ISSUE TITLE
Custom handler for cancel button pressed

### ISSUE THREAD

**Issue by jadore801120** [itsmeichigo/DateTimePicker#30]
Hi, I would like to know when is the user press the cancel button, but it looks like to be fixed to only dismiss view when the cancel button pressed.
Is there any way to detect this event?

Thanks!

Yu-Hsiang

**Comment by GlisboaDev** [comment]
I added it on PR #36 , now we just need someone to merge it for us!

**Comment by itsmeichigo** [comment]
Merged #36
