### ISSUE TITLE
iOS 8 support

### ISSUE THREAD

**Issue by udeysri** [itsmeichigo/DateTimePicker#34]
Is there anyway that I can use this library with iOS 8 support ?

**Comment by itsmeichigo** [comment]
Hi, I will check on iOS 8 to see if there's any issue and let you know.
Thanks.

**Comment by udeysri** [comment]
Hi, thanks for the quick response. It didn't work with Cocoapod when I used iOS 8 as deployment target. But when I added the library files manually it did work fine. Thanks a lot for the great library.

**Comment by aloveric** [comment]
It works on iOS 8. Really good~~
