### ISSUE TITLE
Please delete this 

### ISSUE THREAD

**Issue by siyavash4812** [itsmeichigo/DateTimePicker#37]

**Comment by itsmeichigo** [comment]
Hi, 
Thanks for using the library. Have you set your desired `minimumDate` when showing the date picker? Sorry for not updating the documentation with detailed instructions - but you should find the param in the `show` function.  The `minimumDate` makes sure that user aren't allowed to select a date earlier that the set date.

**Comment by siyavash4812** [comment]
Thank you very much, Yes i just realised that. Sorry for making an issue for that
