### ISSUE TITLE
Taking some time to show DateTimePicker.

### ISSUE THREAD

**Issue by Rashesh-Bosamiya** [itsmeichigo/DateTimePicker#39]
If I have following initializer. It takes some time to present.

`DateTimePicker.show(selected: Date.init(), minimumDate: nil, maximumDate: nil)`

And If I have following Initializer. Picker present immediately.

`DateTimePicker.show()`

**Comment by StevenVerheyen** [comment]
Confirmed. It takes like 1-2 seconds before the picker is being displayed. But! If you specify a minimum date, this is not an issue anymore :) So in my case I needed that minimum date to be the current date :) Perhaps this can help you too?
