### ISSUE TITLE
Simply doesn't work for me

### ISSUE THREAD

**Issue by JOyo246** [itsmeichigo/DateTimePicker#40]
`
    @IBAction func endDatePressed(_ sender: Any) {
        
        let min = Date()
        let max = Date().addingTimeInterval(60 * 60 * 24 * 4)
        let picker = DateTimePicker.show(minimumDate: min, maximumDate: max)
        picker.highlightColor = UIColor(red: 255.0/255.0, green: 138.0/255.0, blue: 138.0/255.0, alpha: 1)
        picker.darkColor = UIColor.darkGray
        picker.doneButtonTitle = "Done"
        picker.todayButtonTitle = "Today"
        picker.is12HourFormat = true
        picker.dateFormat = "hh:mm aa dd/MM/YYYY"
        //        picker.isDatePickerOnly = true
        picker.completionHandler = { date in
            let formatter = DateFormatter()
            formatter.dateFormat = "hh:mm aa dd/MM/YYYY"
            self.endField.text = formatter.string(from: date)
        }
        
        
    }
`
Here's a video
http://tinypic.com/player.php?v=6itsvq%3E&s=9#.Waz0OtsUW_I

**Comment by Rashesh-Bosamiya** [comment]
What is the problem?

**Comment by JOyo246** [comment]
Watch the video, when I scroll to a number, it goes to a completely different number

**Comment by itsmeichigo** [comment]
This issue was fixed in latest commit.
