### ISSUE TITLE
Timewheel automatically scrolling to random dates after swipe select.

### ISSUE THREAD

**Issue by sebamisc** [itsmeichigo/DateTimePicker#42]
I am having a strange issue with DateTimePicker. When swiping the time wheel it automatically scrolls to some seemingly random date. Only happens on iOS 11, built with Xcode 9. On tapping times, it works correctly, only swiping breaks it.

Using: DateTimePicker (1.1.2) through Cocoapods, Swift 3

This is my code;

```
let date = self.defaultDate()
let minDate = Date().addingTimeInterval(24*60*60)

let picker = DateTimePicker.show(selected: date, minimumDate: minDate, maximumDate: nil)
picker.highlightColor = Color.pink.base
picker.tintColor = Color.pink.base
picker.doneButtonTitle = "Set date"
picker.completionHandler = { date in

let dateString = DateHelper.shared.isoDateString(date: date)
    self.currentDate = dateString
}
```

**Comment by itsmeichigo** [comment]
Hi,

This bug is fixed on latest commit, it'd be great if you can check it and see if it works for you. I'll update cocoapods version asap though.

Thanks.

**Comment by sebamisc** [comment]
@itsmeichigo will wait for the cocoa version to verify - do you have a timeline?

**Comment by itsmeichigo** [comment]
I've just pushed version 1.1.3 that fixes the bug. I'll push 1.2.0 for swift 4 later.
Try it out and let me know how it works.

**Comment by higalex** [comment]
@itsmeichigo Thanks a lot for the fix, but there is still a small issue where the hour / minute cells get shifted after scrolling when they go across 0. Please take a look at the video attached.

[ScreenRecording_10-02-2017 23:43.MP4.zip](https://github.com/itsmeichigo/DateTimePicker/files/1349404/ScreenRecording_10-02-2017.23.43.MP4.zip)

**Comment by itsmeichigo** [comment]
Thanks, I'll see what I can do about this issue.

**Comment by sebamisc** [comment]
can confirm fix :)
