### ISSUE TITLE
Setting todayButtonTitle is pushing title to right edge of screen

### ISSUE THREAD

**Issue by akhilcb** [itsmeichigo/DateTimePicker#46]
I am using version 1.1.4 using cocoapods and noticed an issue while setting `todayButtonTitle`. If I set any text, it moves the title to right edge of screen as shown in image. I am using this version because I need only time picker without dates. 

<img width="444" alt="datetimetitleissue" src="https://user-images.githubusercontent.com/11095693/31582535-fe21adee-b13a-11e7-8ce9-a83fd87dfe88.png">

**Comment by itsmeichigo** [comment]
I updated 1.1.4 with the fix. Please update pod and see if it works for you.
Thanks for reporting!

**Comment by akhilcb** [comment]
Thanks for the quick fix. Appreciate that.
