### ISSUE TITLE
how to set the picker for time only??

### ISSUE THREAD

**Issue by ahmediosDeveloper** [itsmeichigo/DateTimePicker#47]
i found , you said i can make it time only , but i dont find property  for that option

**Comment by itsmeichigo** [comment]
Hi, please use `picker.isTimePickerOnly = true`, that should work for you.

**Comment by ahmediosDeveloper** [comment]
thank you , i found this if i installed library manually , but when i installed it through cocoa pods it was not enabled there and  this property was undefind

**Comment by itsmeichigo** [comment]
Please try updating the pod again, I think this feature should be available since the last update.
