### ISSUE TITLE
[Request] Custom data

### ISSUE THREAD

**Issue by GustavoAlvarez** [itsmeichigo/DateTimePicker#49]
Hi, I want to know if its possible to add an option to use custom data apart from dates like an array of names, it would be awesome, thanks.

**Comment by itsmeichigo** [comment]
Thanks for the suggestion. One thing that would need to be considered is that this will require a big change in UI. Currently we're having 2/3 columns for time - I'm not sure where the column custom data should go. Or do you mean you want to replace the time columns entirely with the custom data?

**Comment by GustavoAlvarez** [comment]
yeah I just want to replace the time/date columns and use just one column to fill with the custom data, like a simple picker with one column
![captura de pantalla 2017-11-01 a la s 10 02 42](https://user-images.githubusercontent.com/10645951/32284154-4d10a5ba-bef4-11e7-9311-c76a29fb5876.png)
