### ISSUE TITLE
[question / enhancement ] Only show 15 min selection in minutes table

### ISSUE THREAD

**Issue by alessandrostone** [itsmeichigo/DateTimePicker#5]
Is it possible already to easily just select 15 minutes as selectable options in minutes table?

if not.. suggestions to easily implement that feature ( I could have some spare time to tackle that) ?

**Comment by daviskoh** [comment]
any update on this? i notice the referenced PR is closed

**Comment by itsmeichigo** [comment]
Updated in latest commit. Closing this issue.
