### ISSUE TITLE
Range

### ISSUE THREAD

**Issue by ameetrise1** [itsmeichigo/DateTimePicker#57]
How can I activate or deactivate time picker range? It is not allowing me to pick the time from past which i need to. (eg: Its 5:30 pm I need to pick 4:30 pm, which i cant)

**Comment by itsmeichigo** [comment]
Hi,

Sorry for the late reply. In order to pick a time further back to the past, you should set the min date for the picker some time way back. Please take a look at the demo project to see how you can set the min date in the init method. 

Thanks
