### ISSUE TITLE
Not able to get time in 24 hour format

### ISSUE THREAD

**Issue by ghost** [itsmeichigo/DateTimePicker#61]
I gave **picker.is12HourFormat = true**  to get time in 24 hour format

but am not able to get it in 24 hour format

func dateTimePicker(_ picker: DateTimePicker, didSelectDate: Date){
  print(picker.selectedDateString).   // 08:53 PM 2018-04-02
 instead of 08: 53 PM I need output as 20:53
}
Could any one help me regarding this ?

**Comment by itsmeichigo** [comment]
Hi, 

If you want the 24hr format, please set is12HourFormat to false. 

Thanks
