### ISSUE TITLE
blur effect or dim screen effect when show dialog

### ISSUE THREAD

**Issue by fukemy** [itsmeichigo/DateTimePicker#66]
hello. Thanks you for great library.
I think it would be better when implment blur effect or dim screen effect when show dialog

**Comment by itsmeichigo** [comment]
Hi, there's a property named `backgroundViewColor` that you can use to set the background color for the view behind the picker. I'm also working on making it possible to create the picker as a separate view - when it's done you can use it and create your own blur effect if necessary.
