### ISSUE TITLE
completionHandler is not called

### ISSUE THREAD

**Issue by suatkarakusoglu** [itsmeichigo/DateTimePicker#67]
completionHandler which corresponds to doneButton tap gesture is redirected to dismiss action only. 
I think done button should call completionHandler block.

Thanks.
For example: 

doneButton.addTarget(self, action: #selector(DateTimePicker.didComplete(sender:)), for: .touchUpInside)

@objc
public func didComplete(sender: UIButton?=nil) 
{
      self.completionHandler?(self.selectedDate)
      self.dismissHandler?()
}

**Comment by itsmeichigo** [comment]
Thanks - this will be fixed in version 2.0.1

**Comment by suatkarakusoglu** [comment]
You'r very welcome, thanks for immediate action.
