### ISSUE TITLE
Locale default should be current locale instead of American English

### ISSUE THREAD

**Issue by suatkarakusoglu** [itsmeichigo/DateTimePicker#68]
Hi there,
Locale as default set as american english. But isn't it appropriate to set as current locale.

    /// date locale (language displayed), default to American English
    public var locale = Locale(identifier: "en_US") {
        didSet {
            configureView()
        }
    }

    /// date locale (language displayed), default to Current
    public var locale = Locale.current {
        didSet {
            configureView()
        }
    }

**Comment by itsmeichigo** [comment]
Thanks, this will be fixed in version 2.0.1
