### ISSUE TITLE
display second in time picker

### ISSUE THREAD

**Issue by fukemy** [itsmeichigo/DateTimePicker#77]
Hi. I didnt find the method to include second in timepicker, can u give some suggest? Thanks

**Comment by TonyH-Salient** [comment]
@itsmeichigo Are you planning to add a "seconds" column into to picker anytime soon?

**Comment by itsmeichigo** [comment]
@tonyhoang999 Second column has been added in ver 2.4.0, please update and enjoy!

**Comment by TonyH-Salient** [comment]
Thank so much! Appreciated!
