### ISSUE TITLE
When we call delegates memory is not released 

### ISSUE THREAD

**Issue by awaismubeen** [itsmeichigo/DateTimePicker#80]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Library and Device details (please complete the following information):**
 - Library version: [e.g. 2.1.0]

**Additional context**

**Comment by awaismubeen** [comment]
we have to nil the delegates in completion handlers to release the memory  
picker.completionHandler = { [weak self] date in
            if let weakSelf = self {
                  picker.delegate = nil
             }
}
same as in cancel

**Comment by itsmeichigo** [comment]
Thanks for reporting the issue. I just pushed a commit to fix the issue.

**Comment by awaismubeen** [comment]
Welcome

Regards
*Awais Mubeen*
