### ISSUE TITLE
Not show today in scroll view If change selectedDate to 24 hours before to today 00:00

### ISSUE THREAD

**Issue by damozhang** [itsmeichigo/DateTimePicker#81]
**Describe the bug**
Not show "today" in scroll view if you change selectedDate to 24 hours before to today 00:00

**To Reproduce**
1. Call the DateTimePicker

```
func chooseDatetime(minDate: Date, maxDate: Date, selectedDate: Date?, completion: ((_ date: Date)->Void)?) {
    print("minDate: \(minDate)")
    print("maxDate: \(maxDate)")
    print("selectedDate: \(String(describing: selectedDate))")

    let picker = DateTimePicker.create(minimumDate: minDate, maximumDate: maxDate)
    if let selectedDate = selectedDate {
        picker.selectedDate = selectedDate
    }
    picker.delegate = self
    picker.completionHandler = {date in
        completion?(date)
    }

    picker.frame = CGRect(x: 0, y: 100, width: picker.frame.size.width, height: picker.frame.size.height)
    self.view.addSubview(picker)

    self.datetimePicker = picker
    self.datetimePicker?.show()
}
```
2. Choose yesterday and set time, example:
 If now is 1/29 12:24 PM, you should choose 1/28 12:25 PM
<img width="469" alt="screen shot 2019-01-29 at 12 24 16 pm" src="https://user-images.githubusercontent.com/244297/51938019-dd991180-23c0-11e9-8ceb-1e8fa608e183.png">

```
minDate: 2019-01-22 20:24:04 +0000
maxDate: 2019-01-29 20:24:05 +0000
selectedDate: Optional(2019-01-29 20:24:04 +0000)
```

3. Tap done and set selectedDate to the date you choose

4. Call the DateTimePicker again, "29" disappeared
<img width="469" alt="screen shot 2019-01-29 at 12 24 34 pm" src="https://user-images.githubusercontent.com/244297/51938060-facde000-23c0-11e9-9a8e-7e254898dcda.png">

```
minDate: 2019-01-21 20:25:00 +0000
maxDate: 2019-01-29 20:24:28 +0000
selectedDate: Optional(2019-01-28 20:25:00 +0000)
```

**Library and Device details (please complete the following information):**
 - Library version: 2.1.2
 - Device:  iPhone XS Max
 - OS:  iOS12

**Additional context**
#60

**Comment by sindhugudivada** [comment]
@damozhang   are you doing calling  chooseDatetime in viewDidLoad? Please advise. I tried using this library with no luck.

**Comment by itsmeichigo** [comment]
@damozhang hi, sorry for the late response. I'm not sure why you had to both add the picker as subview and call `show()` at the same time? You should do either one, because `show()` means presenting the picker modally.

**Comment by itsmeichigo** [comment]
Also, it's not clear from your code snippet how you set your maximum and minimum dates. But the picker will only show the dates within the range you set, so if a date disappears, it's probably due to your min-max date range. If you read the source code, you'll see this:
```todayButton.isHidden = self.minimumDate.compare(Date()) == .orderedDescending || self.maximumDate.compare(Date()) == .orderedAscending```

So if you don't set the min and max dates properly, the today button will be hidden to avoid weird behaviors.
