### ISSUE TITLE
font

### ISSUE THREAD

**Issue by lexspirtes** [itsmeichigo/DateTimePicker#86]
can you currently customize the font?

**Comment by dmwesterhoff** [comment]
Bump +1 
One of the main flaws of DatePicker as most people know is customizing appearance is not possible.

**Comment by itsmeichigo** [comment]
Thanks for the idea, but i'm pretty caught up with work lately and can't really make frequent updates. Since this project is open sourced, you guys are welcome to make contributions rather than "placing orders".
