### ISSUE TITLE
Embed picker in the page

### ISSUE THREAD

**Issue by natacodes** [itsmeichigo/DateTimePicker#9]
Hi,

Thanks for your work! Could you help me to figure out how to embed that picker inside the page? So it doesn't pop up on a button press but is always shown on the page.

Thanks!

**Comment by itsmeichigo** [comment]
Good idea. I'll include this feature in the next release, along with auto layout.

**Comment by Sharkesm** [comment]
@itsmeichigo That would be great yay! 💯

**Comment by ened** [comment]
@itsmeichigo There's a AutoLayout PR waiting for you.. will you merge it?

**Comment by itsmeichigo** [comment]
@ened Yes, I will merge it soon when one issue in the PR is fixed. Then I'll have to tweak the lib a little to make embedding possible.

**Comment by itsmeichigo** [comment]
New version 2.0 has supported this. I have also updated the doc for easier integration. Please try this out and let me know if there's any issue.
