### ISSUE TITLE
Support for Dark Mode

### ISSUE THREAD

**Issue by ChopinDavid** [itsmeichigo/DateTimePicker#90]
As you likely know, iOS 13 introduced dark mode. When in dark mode, the table views for showing the hour, minute, and am/pm default to black. There doesn't seem to be a way to change the colors of these table views, and the only way to change the background surrounding it to black is to do something like this:

```swift
if #available(iOS 13.0, *), traitCollection.userInterfaceStyle == .dark {
    picker.darkColor = UIColor.systemGray
    picker.subviews.first?.backgroundColor = .black
    picker.subviews.first?.subviews[0].backgroundColor = .systemGray6
    picker.subviews.first?.subviews[1].backgroundColor = .systemGray5
}
```
It would be nice, and likely wouldn't require too much work, to have the library adapt for dark mode. You could simply add a boolean called `isDark` to DateTimePicker.swift and set it to `true` if the following condition is met: `if #available(iOS 13.0, *), traitCollection.userInterfaceStyle == .dark`. Then, when setting the default UI appearances for the view, you could reference `isDark` and color the subviews accordingly.

**Comment by itsmeichigo** [comment]
Done in PR #89
