### ISSUE TITLE
Scroll the table view to an out-of-bounds row

### ISSUE THREAD

**Issue by thomashoangvn** [itsmeichigo/DateTimePicker#91]
Hi My friend!
Thanks for you nice responsibility ! 
Our tester touching very very fast scroll times then at the end my app cracked by out-of-bounds row , please find att. image, 
![Screen Shot 2019-12-25 at 15 13 19](https://user-images.githubusercontent.com/29686002/71451787-4ba3af80-27af-11ea-9ecf-2aa3aa06a6e5.png)

with show reason : 
*** Terminating app due to uncaught exception 'NSRangeException', reason: 'Attempted to scroll the table view to an out-of-bounds row (72) when there are only 72 rows in section 0. Table view: <UITableView: 0x15e4a5000; frame = (127.5 146; 60 112); clipsToBounds = YES; gestureRecognizers = <NSArray: 0x283080a20>; layer = <CALayer: 0x283ddecc0>; contentOffset: {0, 2863.5}; contentSize: {60, 2904}; adjustedContentInset: {0, 0, 0, 0}; dataSource: <DateTimePicker.DateTimePicker: 0x16023a0e0; frame = (0 337; 375 330); layer = <CALayer: 0x283cd8e20>>>'
*** First throw call stack:

at DateTimePicker .swift i insert the code in below line 798 and line 973 : 
       if tableView == hourTableView, is12HourFormat, selectedRow > 12 * 3 - 1 {
            selectedRow = selectedRow - 12
        }
        else if tableView == hourTableView, !is12HourFormat, selectedRow > 24 * 3 - 1 {
            selectedRow = selectedRow - 24
        }
        else if tableView == minuteTableView, selectedRow > 60 * 3 - 1 {
            selectedRow = selectedRow - 60
        }
Result: it fine , soled out issues
Thanks you!

**Comment by itsmeichigo** [comment]
Thank you for the help!
