### ISSUE TITLE
Done and Cancel buttons don't work

### ISSUE THREAD

**Issue by GeorgeXCV** [itsmeichigo/DateTimePicker#92]
**Describe the bug**
I can't dismiss this picker at all, Done button does nothing and neither does Cancel.

**To Reproduce**
```
func textFieldDidBeginEditing(_ textField: UITextField) {
        if textField.tag == 4 {
            let min = Date().addingTimeInterval(-60 * 60 * 24 * 4)
            let max = Date().addingTimeInterval(60 * 60 * 24 * 4)
            picker = DateTimePicker.create(minimumDate: min, maximumDate: max)
            picker.frame = CGRect(x: 0, y: 250, width: picker.frame.size.width, height: picker.frame.size.height)
            picker.is12HourFormat = false
            picker.dateFormat = "dd/MM/YYYY HH:mm"
            self.view.addSubview(picker)
        }
       }
```

**Comment by itsmeichigo** [comment]
Hi, in order to get callback for Done and Cancel button, please make sure that you implement `dismissHandler` and `completionHandler`.

**Comment by GeorgeXCV** [comment]
Still don't quite understand. I don't get why dismissView() and donePicking() just aren't called. The buttons have touch gestures to trigger these functions? After adding picker, I only expected to have to code logic for "send date selected here". I have no way to reference the cancel and done buttons, calling dismissHandler does nothing.

**Comment by itsmeichigo** [comment]
Please look again at the demo project, there's sample code there. If you want to be notified when picker is dismissed, use this:
```Swift
       picker.dismissHandler = {
            picker.removeFromSuperview()
        }
```
For `donePicking`, do this:
```Swift
       picker.completionHandler = { date in
            let formatter = DateFormatter()
            formatter.dateFormat = "hh:mm aa dd/MM/YYYY"
            self.title = formatter.string(from: date)
        }
```

If you just want to be notified for selected dates, make sure to set delegate of the picker: 
```picker.delegate = self```

And implement the delegate function:
```Swift
    func dateTimePicker(_ picker: DateTimePicker, didSelectDate: Date) {
        title = picker.selectedDateString
    }
```

**Comment by GeorgeXCV** [comment]
Got it working now. I completely missed the demo project, hence the confusion. Thank you!
