### ISSUE TITLE
Fail to Load Nib

### ISSUE THREAD

**Issue by mariaangelina09** [itsmeichigo/DateTimePicker#96]
I've tried to use this library manually by drop the `Source` folder into my project, but then I got error in these lines :

    guard let dateTimePicker = resourceBundle?.loadNibNamed("DateTimePicker", owner: nil, options: nil)?.first as? DateTimePicker else {
            fatalError("Error loading nib")
        }

I already tried to change it into another loading nib method such as :

    static func loadFromXib<T>(withOwner: Any? = nil, options: [UINib.OptionsKey : Any]? = nil) -> T where T: UIView
    {
        let bundle = Bundle(for: self)
        let nib = UINib(nibName: "\(self)", bundle: bundle)
        guard let view = nib.instantiate(withOwner: withOwner, options: options).first as? T else {
            fatalError("Could not load view from nib file.")
        }
        return view
    }

But all I got is a blank screen, could you please help me? Thank you.

**Comment by itsmeichigo** [comment]
Sorry for the bug, I didn't test with this case 😅For quick fix please make sure that the `resourceBundle` is main bundle so you can find the xib file:
```
private static var resourceBundle: Bundle? {
        let podBundle = Bundle(for: DateTimePicker.self)
        guard let bundleURL = podBundle.url(forResource: "DateTimePicker", withExtension: "bundle") else {
            return Bundle.main
        }
        return Bundle(url: bundleURL)
    }
```

Also in the `DateTimePicker.xib` and `FullDateCollectionViewCell.xib` files, please make sure that module of custom class is empty and `Inherit Module from Target` is selected like below:

<img width="259" alt="Screen Shot 2020-03-15 at 11 21 31 AM" src="https://user-images.githubusercontent.com/5533851/76695246-5f282d80-66af-11ea-9148-59391c834df5.png">
<img width="258" alt="Screen Shot 2020-03-15 at 11 37 20 AM" src="https://user-images.githubusercontent.com/5533851/76695402-79630b00-66b1-11ea-8d6b-590e85cb4e2e.png">
<img width="256" alt="Screen Shot 2020-03-15 at 11 37 34 AM" src="https://user-images.githubusercontent.com/5533851/76695405-7ec05580-66b1-11ea-874a-3a087d476300.png">

I'll update the library as soon as I can, hopefully my fix above helps.
