### ISSUE TITLE
isdateinweekend not working as expected

### ISSUE THREAD

**Issue by ssshah** [itsmeichigo/DateTimePicker#97]
**Describe the bug**
when a date is picked from picker to check whether it is in weekend or not. 'isdateinweekend' this method returns false.  

**To Reproduce**
1. select any date that is a sunday
2. then check 'isdateinweekend'
3. it return false.

**Expected behavior**
it should return true for both Sunday and Saturday

**Library and Device details (please complete the following information):**
- OS : iOS 12.3

**Comment by itsmeichigo** [comment]
Is your `Calendar` other than `current`? `DateTimePicker` is only working with `current` instance of Calendar, if you're using custom `Calendar` I will have to add option to customize it for the picker also.
